AspNetMvc.UI/Models/Common/Errors.cs
namespace AspNetMvc.UI.Models.Common
{
    public class Errors
    {
        public int Code { get; set; }

        public int? SourceCode { get; set; }

        public int? Degree { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string Message { get; set; }
    }
}

AspNetMvc.UI/Models/Security/User.cs
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace AspNetMvc.UI.Models.Security
{
    public class User
    {
        [DisplayName("Identificador")]
        public int UsuarioId { get; set; }

        [Required]
        [StringLength(200, ErrorMessage = @"O nome deve ter tamanho no máximo 200.")]
        public string Nome { get; set; }

        [StringLength(50, ErrorMessage = @"O apelido deve ter tamanho no máximo 50.")]
        public string Apelido { get; set; }

        [StringLength(200, ErrorMessage = @"O endereço eletrônico deve ter tamanho no máximo 200.")]
        public string Email { get; set; }

        [Required]
        [StringLength(30, ErrorMessage = @"O login deve ter tamanho no máximo 20.")]
        public string Login { get; set; }

        [Required]
        [StringLength(20, ErrorMessage = @"A senha deve ter tamanho no máximo 20.")]
        public string Senha { get; set; }

        public int? UsuarioTipoId { get; set; }

        public DateTime CadastroDataHora { get; set; }

        public int CadastroUsuarioId { get; set; }

        public DateTime? AtualizacaoDataHora { get; set; }

        public int? AtualizacaoUsuarioId { get; set; }

    }
}

AspNetMvc.UI/Models/Security/UserViewModel.cs
using PagedList;
using System;
using System.Collections.Generic;

namespace AspNetMvc.UI.Models.Security
{
    [Serializable]
    public class UserViewModel
    {
        public UserViewModel()
        {
            User = new User();
            Users = new List<User>().ToPagedList(1, 1);
            Message = string.Empty;
            Success = false;
            PersistFields = false;  
        }

        public User User { get; set; }

        public String Message { get; set; }

        public bool Success { get; set; }

        public bool PersistFields { get; set; }

        public IPagedList<User> Users { get; set; }

    }
}

AspNetMvc.UI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AspNetMvc.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return Redirect("~/User/Index");
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

AspNetMvc.UI/Controllers/UserController.cs
using AspNetMvc.UI.Models.Security;
using PagedList;
using System;
using System.Configuration;
using System.Web.Mvc;

namespace AspNetMvc.UI.Controllers
{
    public class UserController : Controller
    {
        [HttpGet]
        public ActionResult Index(int page = 1)
        {
            var vw = new UserViewModel();
            int pageSize = Convert.ToInt16
                (ConfigurationManager.AppSettings["QuantityRegistrationPage"]);
            int pageNumber = page;

            var users = Services.Security.User.UserList(new Models.Security.User
            {
            });
            if (users != null)
                vw.Users = users.ToPagedList(pageNumber, pageSize);

            return View(vw);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ActionName("Create")]
        public ActionResult Create(UserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var ret = Services.Security.User.UserCreate(model);
                if (!ret.Success)
                {
                    return View(ret);
                }
                else
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                return View(model);
            }
        }

        [HttpGet]
        public ActionResult Edit(User user)
        {
            if (user == null)
                user = new User();

            var UsuarioId = user.UsuarioId;

            return View(new UserViewModel
            {
                Message = string.Empty,
                Success = false,
                PersistFields = false,
                User = user
            });
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View();
        }
    }
}

AspNetMvc.UI/Controllers/UsersController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AspNetMvc.UI.Models.Security;
using PagedList;

namespace AspNetMvc.UI.Controllers
{
    public class UsersController : Controller
    {
        [HttpGet]
        public ActionResult Index(int page = 1)
        {
            var vw = new UserViewModel();
            int pageSize = Convert.ToInt16
                (ConfigurationManager.AppSettings["QuantityRegistrationPage"]);
            int pageNumber = page;

            var users = Services.Security.User.UserList(new Models.Security.User
            {
            });
            if (users != null)
                vw.Users = users.ToPagedList(pageNumber, pageSize);

            return View(vw);
        }

        [HttpGet]
        public ActionResult Create()
        {
            int x = 10;
            return View("~/Views/Users/Create.cshtml");
        }

        [HttpGet]
        public ActionResult Edit()
        {
            return View("Edit.cshtml");
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            return View();
        }
    }
}

AspNetMvc.UI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AspNetMvc.UI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

AspNetMvc.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

AspNetMvc.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meu Aplicativo ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nome do aplicativo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    <li>@Html.ActionLink("Usuário", "Index", "User")</li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meu Aplicativo ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

AspNetMvc.UI/Views/User/Create.cshtml
@model AspNetMvc.UI.Models.Security.UserViewModel

@{
    ViewBag.Title = "Usuario";
}

@using (Html.BeginForm("Create", "User", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new
{
    @class = "form-horizontal",
    role = "form"
}))
{
    @Html.HiddenFor(model => model.User.UsuarioId, new { @Id = "UsuarioId" })
    @Html.HiddenFor(model => model.User.Nome, new { @Id = "Nome" })
    @Html.HiddenFor(model => model.User.Apelido, new { @Id = "Apelido" })
    @Html.HiddenFor(model => model.User.Email, new { @Id = "Email" })
    @Html.HiddenFor(model => model.User.Login, new { @Id = "Login" })
    @Html.HiddenFor(model => model.User.Senha, new { @Id = "Senha" })
    @Html.HiddenFor(model => model.PersistFields, new { @Id = "PersistFields" })

<section>

    <h2>Cadastrar Novo Usuário</h2>

    @{
        var modelUser = new AspNetMvc.UI.Models.Security.UserViewModel();
        if (Model != null)
        {
            modelUser = Model;
        }
    }

    @Html.Partial("Shared", modelUser)

    <div class="row form-group">
        <br />
        <div class="col-md-12">
            <button type="submit" class="btn btn-primary" onclick="beforeSubmit()">
                <span class="glyphicon glyphicon-floppy-saved"></span> Salvar
            </button>
            <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Index", "User")'">
                <span class="glyphicon glyphicon-circle-arrow-left"></span> Voltar
            </button>
        </div>
    </div>

</section>
}

AspNetMvc.UI/Views/User/Edit.cshtml
@model AspNetMvc.UI.Models.Security.UserViewModel

@{
    ViewBag.Title = "Usuario";
}

@using (Html.BeginForm("Create", "User", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new
{
    @class = "form-horizontal",
    role = "form"
}))
{
    @Html.HiddenFor(model => model.User.UsuarioId, new { @Id = "UsuarioId" })
    @Html.HiddenFor(model => model.User.Nome, new { @Id = "Nome" })
    @Html.HiddenFor(model => model.User.Apelido, new { @Id = "Apelido" })
    @Html.HiddenFor(model => model.User.Email, new { @Id = "Email" })
    @Html.HiddenFor(model => model.User.Login, new { @Id = "Login" })
    @Html.HiddenFor(model => model.User.Senha, new { @Id = "Senha" })
    @Html.HiddenFor(model => model.PersistFields, new { @Id = "PersistFields" })
    
    <section>

        <h2>Editar Usuário</h2>

        @{ 
            var modelUser = new AspNetMvc.UI.Models.Security.UserViewModel();
            if (Model != null)
            {
                modelUser = Model;
            }
        }

        @Html.Partial("Shared", modelUser)

        <div class="row form-group">
            <br />
            <div class="col-md-12">
                <button type="submit" class="btn btn-primary" onclick="beforeSubmit()">
                    <span class="glyphicon glyphicon-floppy-saved"></span> Salvar
                </button>
                <button type="button" class="btn btn-default" onclick="location.href='@Url.Action("Index", "User")'">
                    <span class="glyphicon glyphicon-circle-arrow-left"></span> Voltar
                </button>
            </div>
        </div>

    </section>

}

AspNetMvc.UI/Views/User/Index.cshtml
@model AspNetMvc.UI.Models.Security.UserViewModel

@{
    ViewBag.Title = "Index";
}

<div class="col-md-12 filtro">

    @using (Html.BeginForm("Index", "User", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new
    {
        @class = "form-horizontal",
        role = "form"
    }))
    {
        <div class="container">

            <h4>Usuários</h4>

            <div class="form-group col-md-12" style="margin-left: 0em !important;margin-top: 2em !important;padding-left: 0em !important">
                <div class="form-inline col-md-12" style="min-height: 3em !important">
                    <div class="form-group col-md-8" style="padding: 0em !important">
                        <label for="userName">Nome:</label>
                        <input type="text" class="form-control" id="userName" placeholder="Informe o nome do usuário"
                               style="width: 90% !important">
                        @Html.ValidationMessageFor(m => m.Users.First().Nome, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4">
                        <button type="submit" class="btn btn-default" onclick="beforeSubmit()">Consultar</button>
                    </div>
                </div>
            </div>

            <div class="col-md-12 jump-line">&nbsp;</div>

            <div class="col-md-12" style="padding: 0em !important;">
                @Html.ActionLink("Cadastrar", "Create", "Create", new { @class = "btn btn-primary" })
                @*<button class="btn btn-primary"
                            onclick="location.href='/User/Create/'">
                        Cadastrar
                    </button>*@
            </div>

            <div class="col-md-12 jump-line">&nbsp;</div>

            <div class="col-md-12" style="min-height: 2em !important;vertical-align: middle">
                <section id="labelRegistro">
                    <div class="row form-row-two-lines">
                        <div class="col-md-1 label-listing form-text-center form-tow-lines">@Html.Label("Id")</div>
                        <div class="col-md-3 label-listing form-text-center form-tow-lines">@Html.LabelFor(m => m.Users.First().Nome)</div>
                        <div class="col-md-2 label-listing form-text-center form-tow-lines">@Html.LabelFor(m => m.Users.First().Apelido)</div>
                        <div class="col-md-1 label-listing form-text-center form-tow-lines">@Html.LabelFor(m => m.Users.First().Login)</div>
                        <div class="col-md-1 label-listing form-text-center form-tow-lines">@Html.Label("Atualizado Em")</div>
                        <div class="col-md-1 label-listing form-text-center form-tow-lines">@Html.Label("Atualizado Por")</div>
                        <div class="col-md-1 label-listing form-text-center form-tow-lines">Ações</div>
                    </div>
                </section>
            </div>

            <div class="col-md-12">
                <section id="labelRegistro">
                    @{
                        if (Model.Users != null)
                        {
                            foreach (var item in Model.Users)
                            {
                                //  Obtém os campos demonstrados no grid de resultado.
                                var cadastroDataHora = item.CadastroDataHora;
                                var cadastroUsuarioId = item.CadastroUsuarioId;
                                var atualizacaoDataHora = item.AtualizacaoDataHora;
                                var atualizacaoUsuarioId = item.AtualizacaoUsuarioId;
                                var atualizacaoUsuarioNome = string.Empty;
                                var dataHora = string.Empty;
                                if (atualizacaoDataHora != null)
                                {
                                    dataHora = DateTime.Parse(item.AtualizacaoDataHora.ToString()).ToString("dd/MM/yyyy").Trim().Substring(0, 10);
                                }
                                else if (cadastroDataHora != null)
                                {
                                    dataHora = DateTime.Parse(item.CadastroDataHora.ToString()).ToString("dd/MM/yyyy").Trim().Substring(0, 10);
                                }
                                //  Exibe os conteúdos recuperados no grid de resultado.
                                <div class="row">
                                    <div class="col-md-1 content-listing form-text-center">@item.UsuarioId</div>
                                    <div class="col-md-3 content-listing">@item.Nome</div>
                                    <div class="col-md-2 content-listing">@item.Apelido</div>
                                    <div class="col-md-1 content-listing">@item.Login</div>
                                    <div class="col-md-1 content-listing form-text-center">@dataHora</div>
                                    <div class="col-md-1 content-listing form-text-center">@atualizacaoUsuarioNome</div>
                                    <div class="col-md-1 content-listing form-text-center">
                                        @Html.ActionLink("Editar", "Edit", new
                                        {
                                            UsuarioId = item.UsuarioId,
                                            Nome = item.Nome,
                                            Apelido = item.Apelido,
                                            Email = item.Email,
                                            Login = item.Login,
                                            Senha = item.Senha,
                                            UsuarioTipoId = item.UsuarioTipoId,
                                            CadastroDataHora = item.CadastroDataHora,
                                            CadastroUsuarioId = item.CadastroUsuarioId,
                                            AtualizacaoDataHora = item.AtualizacaoDataHora,
                                            AtualizacaoUsuarioId = item.AtualizacaoUsuarioId
                                        })
                                    </div>
                                </div>
                            }
                        }
                    }
                </section>

            </div>

        </div>
    }

</div>

@section Scripts {
    <script type="text/javascript">

        /*
        ** Inicializa toda a página parcial ou view Hotel.
        */
        $(document).ready(function () {

            let $userName = $("#userName");
            if ($userName != null) {
                $userName.focus();
            }

        });

        var beforeSubmit = function () {

            let isValid = true;
            let message = '';

        }

    </script>
}

AspNetMvc.UI/Views/User/Shared.cshtml
@model AspNetMvc.UI.Models.Security.UserViewModel

<div class="row form-group">
    <div class="col-md-3">
        <label for="viewUsuarioId">Identificador</label>
        <input type="text" class="form-control" id="viewUsuarioId" name="viewUsuarioId"
               aria-describedby="usuarioIdHelp" placeholder=""
               value="@Model.User.UsuarioId" disabled />
    </div>
    <div class="col-md-6">
        <label for="viewNome">Nome</label>
        <input type="text" class="form-control" id="viewNome" name="viewNome"
               value="@Model.User.Nome" aria-describedby="nomeHelp"
               placeholder="Entre com o nome" autofocus />
        @Html.ValidationMessageFor(m=> m.User.Nome, "", new { @class = "text-danger" }) 
    </div>
    <div class="col-md-3">
        <label for="viewApelido">Apelido</label>
        <input type="text" class="form-control" id="viewApelido" name="viewApelido"
               value="@Model.User.Apelido"
               aria-describedby="apelidoHelp" placeholder="Entre com o apelido" />
    </div>
</div>

<div class="row form-group">
    <div class="col-md-6">
        <label for="viewLogin">Login:</label>
        <input type="text" class="form-control" id="viewLogin" name="viewLogin"
               value="@Model.User.Login"
               aria-describedby="loginHelp" placeholder="Entre com o login de acesso" />
        @Html.ValidationMessageFor(m => m.User.Login, "", new { @class = "text-danger" })
    </div>
    <div class="col-md-6">
        <label for="viewSenha">Senha:</label>
        <input type="password" class="form-control" id="viewSenha" name="viewSenha"
               value="@Model.User.Senha"
               aria-describedby="senhaHelp" placeholder="Entre com a senha de acesso">
        @Html.ValidationMessageFor(m => m.User.Senha, "", new { @class = "text-danger" })
    </div>
</div>

<div class="row form-group">
    <div class="col-md-12">
        <label for="email">Email:</label>
        <input type="email" class="form-control" id="viewEmail" name="viewEmail"
               value="@Model.User.Email"
               aria-describedby="emailHelp" placeholder="Entre com o e-mail">
        <small id="emailHelp" class="form-text text-muted">Nós nunca vamos compartilhar seu e-mail com mais ninguém..</small>
    </div>
</div>


<script type="text/javascript">

    /*
    ** Inicializa toda a página parcial ou view Hotel.
    */
    $(document).ready(function () {

        //let $nome = $("#viewNome");
        //if ($nome != null && $nome != undefined) {
        //    $nome.focus();
        //}

    });

    var beforeSubmit = function () {

        let isValid = true;
        let message = '';

        let $usuarioId = $("viewUsuarioId");
        if ($usuarioId != null && $usuarioId != undefined) {
            $("#UsuarioId").val($usuarioId.val());
        }

        let $nome = $("#viewNome");
        if ($nome != null && $nome != undefined) {
            $("#Nome").val($nome.val());
        }

        let $apelido = $("#viewApelido");
        if ($apelido != null && $apelido != undefined) {
            $("#Apelido").val($apelido.val());
        }

        let $email = $("#viewEmail");
        if ($email != null && $email != undefined) {
            $("#Email").val($email.val());
        }

        let $login = $("#viewLogin");
        if ($login != null && $login != undefined) {
            $("#Login").val($login.val());
        }

        let $senha = $("#viewSenha");
        if ($senha != null && $senha != undefined) {
            $("#Senha").val($senha.val());
        }
    }

    var afterSubmit = function () {
    }

</script>

AspNetMvc.UI/Views/Users/Index.cshtml
@model AspNetMvc.UI.Models.Security.UserViewModel

@{
    ViewBag.Title = "Index";
}

<div class="col-md-12 filtro">

    @using (Html.BeginForm("Index", "Users", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new
    {
        @class = "form-horizontal",
        role = "form"
    }))
    {
        <div class="container">

            <h4>Usuários</h4>

            <div class="form-group col-md-12" style="margin-left: 0em !important;margin-top: 2em !important;padding-left: 0em !important">
                <div class="form-inline col-md-12" style="min-height: 3em !important">
                    <div class="form-group col-md-8" style="padding: 0em !important">
                        <label for="userName">Nome:</label>
                        <input type="text" class="form-control" id="userName" placeholder="Informe o nome do usuário"
                               style="width: 90% !important">
                        @Html.ValidationMessageFor(m => m.Users.First().Nome, "", new { @class = "text-danger" })
                    </div>
                    <div class="form-group col-md-4">
                        <button type="submit" class="btn btn-default" onclick="beforeSubmit()">Consultar</button>
                    </div>
                </div>
            </div>

            <div class="col-md-12 jump-line">&nbsp;</div>

            <div class="col-md-12" style="padding: 0em !important;">
                <button class="btn btn-primary"
                        onclick="location.href='@Url.Action("Create", "Users")'">
                    Cadastrar
                </button>
            </div>

            <div class="col-md-12 jump-line">&nbsp;</div>

            <div class="col-md-12" style="min-height: 2em !important;vertical-align: middle">
                <section id="labelRegistro">
                    <div class="row form-row-two-lines">
                        <div class="col-md-1 label-listing form-text-center form-tow-lines">@Html.Label("Id")</div>
                        <div class="col-md-3 label-listing form-text-center form-tow-lines">@Html.LabelFor(m => m.Users.First().Nome)</div>
                        <div class="col-md-2 label-listing form-text-center form-tow-lines">@Html.LabelFor(m => m.Users.First().Apelido)</div>
                        <div class="col-md-1 label-listing form-text-center form-tow-lines">@Html.LabelFor(m => m.Users.First().Login)</div>
                        <div class="col-md-1 label-listing form-text-center form-tow-lines">@Html.Label("Atualizado Em")</div>
                        <div class="col-md-1 label-listing form-text-center form-tow-lines">@Html.Label("Atualizado Por")</div>
                        <div class="col-md-1 label-listing form-text-center form-tow-lines">Ações</div>
                    </div>
                </section>
            </div>

            <div class="col-md-12">
                <section id="labelRegistro">
                    @{
                        if (Model.Users != null)
                        {
                            foreach (var item in Model.Users)
                            {
                                //  Obtém os campos demonstrados no grid de resultado.
                                var cadastroDataHora = item.CadastroDataHora;
                                var cadastroUsuarioId = item.CadastroUsuarioId;
                                var atualizacaoDataHora = item.AtualizacaoDataHora;
                                var atualizacaoUsuarioId = item.AtualizacaoUsuarioId;
                                var atualizacaoUsuarioNome = string.Empty;
                                var dataHora = string.Empty;
                                if (atualizacaoDataHora != null)
                                {
                                    dataHora = DateTime.Parse(item.AtualizacaoDataHora.ToString()).ToString("dd/MM/yyyy").Trim().Substring(0, 10);
                                }
                                else if (cadastroDataHora != null)
                                {
                                    dataHora = DateTime.Parse(item.CadastroDataHora.ToString()).ToString("dd/MM/yyyy").Trim().Substring(0, 10);
                                }
                                //  Exibe os conteúdos recuperados no grid de resultado.
                                <div class="row">
                                    <div class="col-md-1 content-listing form-text-center">@item.UsuarioId</div>
                                    <div class="col-md-3 content-listing">@item.Nome</div>
                                    <div class="col-md-2 content-listing">@item.Apelido</div>
                                    <div class="col-md-1 content-listing">@item.Login</div>
                                    <div class="col-md-1 content-listing form-text-center">@dataHora</div>
                                    <div class="col-md-1 content-listing form-text-center">@atualizacaoUsuarioNome</div>
                                    <div class="col-md-1 content-listing form-text-center">
                                        @Html.ActionLink("Editar", "Edit", new
                                        {
                                            id = item.UsuarioId
                                        })
                                    </div>
                                </div>
                            }
                        }
                    }
                </section>

            </div>

        </div>
    }

</div>

@section Scripts {
    <script type="text/javascript">

        /*
        ** Inicializa toda a página parcial ou view Hotel.
        */
        $(document).ready(function () {

            let $userName = $("#userName");
            if ($userName!= null) {
                $userName.focus();
            }

        });

        var beforeSubmit = function () {

            let isValid = true;
            let message = '';

        }

    </script>
}